Updated dotfiles, switched to zsh (some files may not be included yet), experimental support for dotstrap.sh

diff --git a/.local/bin/compile b/.local/bin/compile
--- a/.local/bin/compile
+++ b/.local/bin/compile
@@ -24,18 +24,11 @@ echo "Compiling $basename..."
 
 cd "$dir" || exit 1
 
-# test for   // [COMPILE]   at beginning of file
-comp_msg="$(head -n 1 "$file" | grep '// \[COMPILE\]')"
-if [ -n "$comp_msg" ]; then
-	comp_msg="$(echo "$comp_msg" | cut -c 13-)"
-	eval "$(printf "$comp_msg" "$file" "$base")"
-else
-	case "$ext" in
-		"cpp"|"cc"|"cxx") g++ "$file" -o "$base" && echo "Compiled C++" ;;
-		"tex") pdflatex "$file" && echo "Compiled LaTeX" ;;
-		"c") gcc "$file" -o "$base" && echo "Compiled C" ;;
-		*) echo "Cannot compile file '$basename'" && exit 1 ;;
-	esac
-fi
+case "$ext" in
+	"cpp"|"cc"|"cxx") g++ "$file" -o "$base" && echo "Compiled C++" ;;
+	"tex") pdflatex "$file" && echo "Compiled LaTeX" ;;
+	"c") gcc "$file" -o "$base" && echo "Compiled C" ;;
+	*) echo "Cannot compile file '$basename'" && exit 1 ;;
+esac
 
 [ -n "$run_after" ] && eval "$base"
